times = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco da Gama', 'Chapecoense', 'Atlético Galão ganhou mais uma vez, ai credo', 'Botafogo', 'Athletico-PR', 'Bahia', 'São Paulo', 'Fluminense', 'Sport Recife', 'EC Vitória', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlético-GO')
print('-='*16)
print(f'Lista dos times do Brasileirão: {times}')
print('-='*16)
print(f'Os 5 primeiros são: {times[0:5]}')
print('-='*16)
print(len(times))
print(f'Os 4 ultimos são: {times[-4:]}')
print('-='*16)
print(f'Os times em ordem alfabética: {sorted(times)}')
print('-='*16)
print(f'O {times[7]} está na 8ª posição')